Started logging messages at Sat Sep 15 15:34:18 2018
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 35 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 62
Info:            Created 
Info:        Working on 82
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 80
Info:            Created 
Info:        Working on 15
Info:            Created 
Info:        Working on 105
Info:            Created 
Info:        Working on 133
Info:            Created 
Info:        Working on 22
Info:            Created 
Info:        Working on 131
Info:            Created 
Info:        Working on 32
Info:            Created 
Info:        Working on 161
Info:            Created 
Info:        Working on 197
Info:            Created 
Info:        Working on 47
Info:            Created 
Info:        Working on 195
Info:            Created 
Info:        Working on 67
Info:            Created 
Info:        Working on 238
Info:            Created 
Info:        Working on 299
Info:            Created 
Info:        Working on 91
Info:            Created 
Info:        Working on 297
Info:            Created 
Info:        Working on 118
Info:            Created 
Info:        Working on 346
Info:            Created 
Info:        Working on 467
Info:            Created 
Info:        Working on 147
Info:            Created 
Info:        Working on 225
Info:            Created 
Info:        Working on 182
Info:            Created 
Info:        Working on 410
Info:            Created 
Info:        Working on 229
Info:            Created 
Info:        Working on 240
Info:            Created 
Info:        Working on 163
Info:            Created 
Info:        Working on 107
Info:            Created 
Info:        Working on 86
Info:            Created 
Info:        Working on 290
Info:            Created 
Info:        Working on 291
Info:            Created 
Info:        Working on 357
Info:            Created 
Info:        Working on 441
Info:            Created 
Info:        Working on 451
Info:            Created 
Info:        Working on 369
Info:            Created 
Info:        Working on 112
Info:            Created 
Info:        Working on 343
Info:            Created 
Info:        Working on 344
Info:            Created 
Info:        Working on 422
Info:            Created 
Info:        Working on 498
Info:            Created 
Info:        Working on 505
Info:            Created 
Info:        Working on 430
Info:            Created 
Info:        Working on 138
Info:            Created 
Info:        Working on 407
Info:            Created 
Info:        Working on 408
Info:            Created 
Info:        Working on 487
Info:            Created 
Info:        Working on 486
Info:            Created 
Info:        Working on 167
Info:            Created 
Info:        Working on 561
Info:            Created 
Info:        Working on 562
Info:            Created 
Info:        Working on 202
Info:            Created 
Info:        Working on 534
Info:            Created 
Info:        Working on 552
Info:            Created 
Info:        Working on 244
Info:            Created 
Info:        Working on 563
Info:            Created 
Info:        Working on 521
Info:            Created 
Info:        Working on 304
Info:            Created 
Info:        Working on 545
Info:            Created 
Info:        Working on 462
Info:            Created 
Info:        Working on 386
Info:            Created 
Info:        Working on 469
Info:            Created 
Info:        Working on 445
Info:            Created 
Info:        Working on 512
Info:            Created 
Info:        Working on 551
Info:            Created 
Info:        Working on 519
Info:            Created 
Info:        Working on 460
Info:            Created 
Info:        Working on 380
Info:            Created 
Info:        Working on 465
Info:            Created 
Info:        Working on 526
Info:            Created 
Info:        Working on 556
Info:            Created 
Info:        Working on 547
Info:            Created 
Info:        Working on 507
Info:            Created 
Info:        Working on 434
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 3.83256e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sat Sep 15 15:34:18 2018
